### ISSUE TITLE
view list of consumers or producers not working in version 1.0.0 burrow

### ISSUE THREAD

**Issue by ghost** [GeneralMills/BurrowUI#10]
i used burrow v 1.0.0. i can view count of consumers and producers on burrowui but for view list of producers or consumers i see below error

>error_handler.js:54 EXCEPTION: Error in ./DisplayConsumersComponent class DisplayConsumersComponent - inline template:11:6 caused by: Cannot read property 'toLowerCase' of undefined
webpackJsonp.../../../core/src/error_handler.js.ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/src/facade/async.js.EventEmitter.emit @ async.js:79
webpackJsonp.../../../core/src/zone/ng_zone.js.NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:338
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:56 ORIGINAL EXCEPTION: Cannot read property 'toLowerCase' of undefined
webpackJsonp.../../../core/src/error_handler.js.ErrorHandler.handleError @ error_handler.js:56
next @ application_ref.js:348
schedulerFn @ async.js:93
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/src/facade/async.js.EventEmitter.emit @ async.js:79
webpackJsonp.../../../core/src/zone/ng_zone.js.NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:338
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:59 ORIGINAL STACKTRACE:
webpackJsonp.../../../core/src/error_handler.js.ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/src/facade/async.js.EventEmitter.emit @ async.js:79
webpackJsonp.../../../core/src/zone/ng_zone.js.NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:338
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:60 TypeError: Cannot read property 'toLowerCase' of undefined
    at http://x.x.x.x:3000/main.bundle.js:117:32
    at Array.sort (native)
    at Array.sort (http://x.x.x.x:3000/polyfills.bundle.js:2981:15)
    at ConsumerSortPipe.webpackJsonp.../../../../../src/app/classes/consumer.ts.ConsumerSortPipe.transform (http://x.x.x.x:3000/main.bundle.js:116:15)
    at View_DisplayConsumersComponent1.detectChangesInternal (/AppModule/DisplayConsumersComponent/component.ngfactory.js:201:69)
    at View_DisplayConsumersComponent1.webpackJsonp.../../../core/src/linker/view.js.AppView.detectChanges (http://x.x.x.x:3000/vendor.bundle.js:99135:14)
    at View_DisplayConsumersComponent1.webpackJsonp.../../../core/src/linker/view.js.DebugAppView.detectChanges (http://x.x.x.x:3000/vendor.bundle.js:99330:44)
    at ViewContainer.webpackJsonp.../../../core/src/linker/view_container.js.ViewContainer.detectChangesInNestedViews (http://x.x.x.x:3000/vendor.bundle.js:99468:37)
    at CompiledTemplate.proxyViewClass.View_DisplayConsumersComponent0.detectChangesInternal (/AppModule/DisplayConsumersComponent/component.ngfactory.js:332:15)
    at CompiledTemplate.proxyViewClass.webpackJsonp.../../../core/src/linker/view.js.AppView.detectChanges (http://x.x.x.x:3000/vendor.bundle.js:99135:14)
    at CompiledTemplate.proxyViewClass.webpackJsonp.../../../core/src/linker/view.js.DebugAppView.detectChanges (http://x.x.x.x:3000/vendor.bundle.js:99330:44)
    at CompiledTemplate.proxyViewClass.webpackJsonp.../../../core/src/linker/view.js.AppView.internalDetectChanges (http://x.x.x.x:3000/vendor.bundle.js:99120:18)
    at View_HomeComponent3.detectChangesInternal (/AppModule/HomeComponent/component.ngfactory.js:74:19)
    at View_HomeComponent3.webpackJsonp.../../../core/src/linker/view.js.AppView.detectChanges (http://x.x.x.x:3000/vendor.bundle.js:99135:14)
    at View_HomeComponent3.webpackJsonp.../../../core/src/linker/view.js.DebugAppView.detectChanges (http://x.x.x.x:3000/vendor.bundle.js:99330:44)
webpackJsonp.../../../core/src/error_handler.js.ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/src/facade/async.js.EventEmitter.emit @ async.js:79
webpackJsonp.../../../core/src/zone/ng_zone.js.NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:338
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:63 ERROR CONTEXT:
webpackJsonp.../../../core/src/error_handler.js.ErrorHandler.handleError @ error_handler.js:63
next @ application_ref.js:348
schedulerFn @ async.js:93
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/src/facade/async.js.EventEmitter.emit @ async.js:79
webpackJsonp.../../../core/src/zone/ng_zone.js.NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:338
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:64 DebugContext {_view: View_DisplayConsumersComponent1, _nodeIndex: 2, _tplRow: 11, _tplCol: 6}
webpackJsonp.../../../core/src/error_handler.js.ErrorHandler.handleError @ error_handler.js:64
next @ application_ref.js:348
schedulerFn @ async.js:93
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/src/facade/async.js.EventEmitter.emit @ async.js:79
webpackJsonp.../../../core/src/zone/ng_zone.js.NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:338
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
Subscriber.js:242 Uncaught ViewWrappedError {__zone_symbol__error: Error: Error in ./DisplayConsumersComponent class DisplayConsumersComponent - inline template:11:6 c……}
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:242
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/src/facade/async.js.EventEmitter.emit @ async.js:79
webpackJsonp.../../../core/src/zone/ng_zone.js.NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:338
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420

**Comment by brusser** [comment]
I also have this issue. Anyone updating this for 1.0.0?

**Comment by cgosiak** [comment]
Yes, I am actively working on getting BurrowUI upgraded for use with Burrow 1.x.

With this being said, I am looking at doing a pretty big rewrite of the project due to other issues with the project.

More information coming soon!

**Comment by 4everinbeta** [comment]
+1

**Comment by joway** [comment]
I have rewrited the UI for v3 API . https://github.com/joway/burrow-dashboard

@pmhossein71 @brusser @cgosiak @4everinbeta

**Comment by adomenech73** [comment]
Hi @cgosiak , do you have any prevision on the BurrowUI upgrade?
Is there any point where we can help?

**Comment by cgosiak** [comment]
Greetings all!

So I have been finding some time to work on this, and have completed the new backend services for Burrow 1.0. My next step will be to integrate that with the UI however, due to past complications Issue #5 , I am looking at rewriting the UI to take advantage of the new backend; as well as bring the project up to Angular 5. Sorry for the wait, just hard to find time :)

**Comment by dangkaka** [comment]
👍
great, thanks a lot 
looking forward to hearing from you soon @cgosiak

**Comment by chetankabra** [comment]
@cgosiak, when will be new updates will be available?
Thanks,
Chetan K

**Comment by petersonnek** [comment]
Hey everyone, this has been deprioritized a bit. There's a chance we might take a look at this around June. We'd we happy to review a PR if someone wants take this on sooner.

**Comment by petersonnek** [comment]
We've finally gotten around to updating to Burrow 1.1.0 and published a new container to Docker Hub.
