### ISSUE TITLE
Push to Docker Hub

### ISSUE THREAD

**Issue by claycephas** [GeneralMills/BurrowUI#4]
Would it be possible to get an image of this pushed to https://hub.docker.com?

**Comment by cgosiak** [comment]
This is something I will look in to; and update on when completed.

**Comment by edkellena** [comment]
Any progress on this @cgosiak ?

**Comment by cgosiak** [comment]
Hello @claycephas and @edkellena ,

Thank you for your patience. I have made the newest image available on docker hub!

This is available at: https://hub.docker.com/r/generalmills/burrowui/

**Comment by edkellena** [comment]
Thanks @cgosiak , that's awesome!  One small documentation PR: https://github.com/GeneralMills/BurrowUI/pull/9

**Comment by claycephas** [comment]
Thanks @cgosiak!
